### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Alpslee** [MandiZhao/robot-collab#3]
assert llm_source in ["gpt-4", "gpt-3.5-turbo", "claude"], f"llm_source must be one of [gpt4, gpt-3.5-turbo, claude], got {llm_source}"
AssertionError: llm_source must be one of [gpt4, gpt-3.5-turbo, claude], got gpt4

I didn't get claude api key, but I get gpt4, do I need to get both of them?thanks.

**Comment by MandiZhao** [comment]
No you don't need both API keys. But the assertion error here is because of my typo in the README, it should be `-llm gpt-4` and not `-llm gpt4`, fixing that now!
