### ISSUE TITLE
Error running `rope` task

### ISSUE THREAD

**Issue by vateseif** [MandiZhao/robot-collab#4]
When I try to run `python run_dialog.py --task rope `, I get the following error:

~~~
ValueError: Error: material 'stove-metal' not found in geom 145
Object name = groove_front, id = 145, line = 55, column = -1
~~~

**Comment by NikoCiminelliTufts** [comment]
Did you by chance get any task to work successfully?

**Comment by vateseif** [comment]
Yeah I was able to run the other tasks

**Comment by NikoCiminelliTufts** [comment]
I have been getting stuck on the display plan error that the other issue raised as well. If you had success running this, would you mind telling me what you changed/ what your parameters were?

**Comment by MandiZhao** [comment]
Hi @NikoCiminelliTufts @vateseif sorry for the late response! It should be fixed now, the issue was due to a missing definition in object_assets.xml, please check the updated task_rope.xml file.
